name: Commit Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run lint script
        run: npm run lint
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
